### ISSUE TITLE
Improve Hebrew/RTL CSS for about/more

### ISSUE THREAD

**Issue by msappir** [Toootim/Discussion#24]
After uploading the new, [Hebrew CoC](https://tooot.im/about/more) (see #1), it became clear the site's CSS doesn't look great there. Anyone have suggestions on how to improve it?

**Comment by elad661** [comment]
This selector `.about-body ul, .about-body ol` has `margin-left: 20px`, when it should be `margin-right` since we're writing Hebrew from right to left.

It can be easily fixed by adding the following to the custom css file:

```css
.about-body .rtl ul, .about-body .rtl ol {
    margin-right: 20px;
    margin-left: 0;
}
````
